### ISSUE TITLE
On posts, images should be right aligned, not centered. 

### ISSUE THREAD

**Issue by avansintjan** [simonv3/unevenearth#5]
The problem is that i used to have to size the first image so as not to collide with the 'recent posts' widget on the sidebar. so ill have to resize all the first images to make them full size. but in any case they shouldn't automatically center, but maybe right align instead? maybe there's a reason for this.

**Comment by simonv3** [comment]
Yeah, so you can change the alignment on the images themselves. If you don't specify an alignment then they'll center align by default. If you want to change it I would recommend that all images have to be changed, rather than changing the code so that even "center aligned" images are right aligned if that makes sense.
